# 1Password SSH Agent Configuration
# Personal machine: personal key only

[[ssh-keys]]
item = "Aaron's github ssh key"
vault = "Private"
account = "my.1password.com"

[[ssh-keys]]
item = "Personal Local Homelab SSH Keys"
vault = "Private"
account = "my.1password.com"
